[tool.poetry]
name = "aqi-prediction-service"
version = "0.1.0"
description = ""
authors = ["PsyRar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
